-- ============================================================================
-- Visit Drakensberg — Directory Contacts + contact segmentation
--
-- The platform's own outreach address book: establishments compiled from the
-- regional tourism directories (Clarens.co.za, Drakensberg Experience,
-- Drakensberg.org, Midlands Meander) that we want on the platform. These are
-- NOT customers and NOT a supplier's address book:
--   * vd_customer_profiles / vd_customer_segments (20260824) are keyed on
--     auth.users — every one of those rows is a real registered account.
--     A directory establishment has no account, so it can't live there.
--   * vd_supplier_contacts (20260826/27/28) is a *supplier's* list of people
--     who booked with them. A prospect we haven't spoken to yet belongs to
--     no supplier at all.
-- Hence a third contact book, sitting alongside those two under /admin/contacts,
-- with the same shape of segmentation the customer side already has:
-- definitions + computed membership + a recompute function, never hand-assigned.
--
-- Segmentation here is rule-driven rather than hardcoded per segment
-- (vd_recompute_segments' eight fixed queries don't generalise to an
-- open-ended set of source sites and regions): each segment carries a small
-- {"type": …, "value": …} rule, and one query evaluates every rule. Segments
-- for the values actually present in the data (source site, region, sector)
-- are generated by the recompute itself, so importing a list from a new
-- directory site or a new region produces its segment automatically.
--
-- Purely additive: no existing table, function or policy is touched.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1. vd_directory_contacts — one row per establishment.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists vd_directory_contacts (
  id                  uuid primary key default gen_random_uuid(),
  establishment       text not null,
  contact_person      text,
  -- Directory listings routinely publish more than one address/number/site
  -- (a reservations and a general mailbox, a landline and a mobile). The
  -- first is kept as the scalar for lists and exports; the array keeps the
  -- rest so nothing published is thrown away at import time.
  email               text,
  emails              text[] not null default '{}',
  phone               text,
  phones              text[] not null default '{}',
  websites            text[] not null default '{}',
  socials             text[] not null default '{}',
  address             text,
  booking_url         text,
  source_listing_urls text[] not null default '{}',
  -- Segmentation dimensions, split out of the source columns at import.
  source_sites        text[] not null default '{}',
  categories          text[] not null default '{}',
  regions             text[] not null default '{}',
  -- Coarse grouping derived from `categories` (82 distinct raw category
  -- tokens across the four source sites is far too granular to segment on).
  -- An establishment can be in several — a guesthouse with a restaurant is
  -- genuinely both, and should appear in both segments.
  sectors             text[] not null default '{}',
  -- How reachable the listing is, as published: 'Email + phone',
  -- 'Email only', 'Phone only', 'Web/social only', 'No direct contact published'.
  contact_status      text,
  verified_on         date,
  -- Outreach workflow — admin-owned, never overwritten by re-importing the
  -- source list (see vd_directory_contacts_upsert below).
  priority            text check (priority is null or priority in ('high', 'medium', 'low')),
  outreach_status     text not null default 'not_contacted'
                        check (outreach_status in ('not_contacted', 'contacted', 'in_conversation', 'converted', 'declined', 'unreachable')),
  last_contacted      date,
  follow_up_date      date,
  owner               text,
  outreach_notes      text not null default '',
  -- Why a listing has no contact details, carried over from the compile.
  data_notes          text not null default '',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
-- The establishment name is the identity of a directory row (there is no
-- account, and 40% of the list publishes no email at all), so re-importing
-- an updated compile updates in place instead of duplicating.
create unique index if not exists vd_directory_contacts_name_uidx on vd_directory_contacts (lower(establishment));
create index if not exists vd_directory_contacts_outreach_idx on vd_directory_contacts (outreach_status);
create index if not exists vd_directory_contacts_followup_idx on vd_directory_contacts (follow_up_date) where follow_up_date is not null;

alter table vd_directory_contacts enable row level security;
drop policy if exists "Admins manage directory contacts" on vd_directory_contacts;
create policy "Admins manage directory contacts" on vd_directory_contacts for all using (is_admin());
-- Internal outreach tooling only — no supplier or visitor path reads this
-- table, so unlike most tables in this schema there is no owner-scoped
-- policy alongside the admin one.

-- ────────────────────────────────────────────────────────────────────────────
-- 2. Segments — definitions + computed membership.
-- ────────────────────────────────────────────────────────────────────────────
create table if not exists vd_contact_segments (
  id            text primary key,
  name          text not null,
  description   text not null default '',
  -- UI grouping: 'Reachability' | 'Outreach' | 'Sector' | 'Source' | 'Region'.
  segment_group text not null default 'Other',
  -- {"type": <rule>, "value": <text>} — see vd_apply_contact_segments below
  -- for the supported rule types. A rule type this database doesn't know
  -- matches nothing rather than erroring.
  rule          jsonb not null,
  -- true for the ones the recompute generates from the data itself (source
  -- site / region / sector); false for the seeded, fixed ones. Only
  -- generated segments are retired when their value disappears from the data.
  is_generated  boolean not null default false,
  sort_order    integer not null default 100,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists vd_contact_segment_members (
  segment_id  text not null references vd_contact_segments(id) on delete cascade,
  contact_id  uuid not null references vd_directory_contacts(id) on delete cascade,
  computed_at timestamptz not null default now(),
  primary key (segment_id, contact_id)
);
create index if not exists vd_contact_segment_members_contact_idx on vd_contact_segment_members (contact_id);

alter table vd_contact_segments enable row level security;
alter table vd_contact_segment_members enable row level security;
drop policy if exists "Admins manage contact segments"     on vd_contact_segments;
drop policy if exists "Admins read contact segment members" on vd_contact_segment_members;
create policy "Admins manage contact segments"      on vd_contact_segments for all using (is_admin());
create policy "Admins read contact segment members" on vd_contact_segment_members for select using (is_admin());
-- Membership is computed, never hand-assigned — same rule as
-- vd_customer_segment_members — so there is no write policy for anyone;
-- vd_apply_contact_segments() below owns every row in it.

insert into vd_contact_segments (id, name, description, segment_group, rule, sort_order) values
  ('reach:email',      'Has Email',            'A published email address — reachable by an outreach campaign', 'Reachability', '{"type":"has_email"}',      10),
  ('reach:phone',      'Has Phone',            'A published phone number',                                      'Reachability', '{"type":"has_phone"}',      20),
  ('reach:both',       'Email + Phone',        'Both an email address and a phone number',                      'Reachability', '{"type":"has_both"}',       30),
  ('reach:none',       'No Direct Contact',    'Nothing published to reach them on — needs research first',     'Reachability', '{"type":"unreachable"}',    40),
  ('outreach:not_contacted',  'Not Contacted',   'No outreach attempted yet',                                   'Outreach',     '{"type":"outreach_status","value":"not_contacted"}',  50),
  ('outreach:contacted',      'Contacted',       'Reached out, no reply yet',                                   'Outreach',     '{"type":"outreach_status","value":"contacted"}',      60),
  ('outreach:in_conversation','In Conversation', 'Actively talking to them',                                    'Outreach',     '{"type":"outreach_status","value":"in_conversation"}',70),
  ('outreach:converted',      'Converted',       'Now listed on the platform',                                  'Outreach',     '{"type":"outreach_status","value":"converted"}',      80),
  ('outreach:declined',       'Declined',        'Said no',                                                     'Outreach',     '{"type":"outreach_status","value":"declined"}',       90),
  ('outreach:follow_up_due',  'Follow-up Due',   'Follow-up date reached and the conversation is still open',   'Outreach',     '{"type":"follow_up_due"}',                          100)
on conflict (id) do update set
  name = excluded.name, description = excluded.description,
  segment_group = excluded.segment_group, rule = excluded.rule,
  sort_order = excluded.sort_order, updated_at = now();

-- ────────────────────────────────────────────────────────────────────────────
-- 3. Category → sector, the only derived field on a contact.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.vd_directory_sectors(p_categories text[])
returns text[]
language sql immutable set search_path = public as $$
  select coalesce(
    nullif(
      array_remove(array[
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'accommodation|self.?catering|guest.?house|bed & breakfast|b&b|^bnb$|hotel|resort|lodge|chalet|camping|caravan|backpack|cottage|farm.?stay')
             then 'Accommodation' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'dining|restaurant|caf|food|eat & drink|beverage|brewery|bakery|deli|pub|bar$|wine|coffee|farm stall|shisanyama')
             then 'Food & Drink' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             -- \y…\y around "tour": "Tourism Information" is a services
             -- listing, not a tour operator.
             where c ~* 'activit|adventure|hiking|horse|\ytours?\y|trail|fishing|golf|xtreme|quad|zip|abseil|canopy|birding|4x4|cycl|mtb|paintball|archery|game drive|leisure')
             then 'Activities & Tours' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'wedding|conferenc|function|venue|events?$')
             then 'Weddings & Events' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'spa|wellness|beauty|salon|massage|makeup|yoga|health')
             then 'Wellness' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'shop|\yarts?\y|artist|craft|galler|gift|decor|antique|nursery|market|studio|pottery|jewel')
             then 'Shopping & Art' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'learning|course|school|workshop|training')
             then 'Learning' end,
        case when exists (select 1 from unnest(coalesce(p_categories, '{}')) c
             where c ~* 'support|repair|roadside|fuel|medical|doctor|vet|security|estate agent|real estate|bank|information|transport|shuttle|services?$')
             then 'Services' end
      ], null),
      '{}'::text[]
    ),
    array['Other']
  )
$$;

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Segment recompute.
--
-- Split in two on purpose: vd_apply_contact_segments() holds the logic and
-- is SECURITY INVOKER with EXECUTE revoked from every client role, so the
-- only callers are the admin-guarded wrappers below (which, being SECURITY
-- DEFINER, run as this migration's owner) and a superuser/service-role
-- session running a data load. That keeps one copy of the rules without
-- exposing an unguarded write path — a SECURITY DEFINER helper with no
-- is_admin() check would be exactly that, since Postgres grants EXECUTE to
-- PUBLIC on new functions by default.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.vd_apply_contact_segments()
returns integer
language plpgsql set search_path = public as $$
declare
  v_count integer;
begin
  -- (a) Generate a segment per value actually present in the data.
  with present as (
    select 'source' as kind, unnest(source_sites) as value from vd_directory_contacts
    union
    select 'region', unnest(regions) from vd_directory_contacts
    union
    select 'sector', unnest(sectors) from vd_directory_contacts
  ),
  defs as (
    -- distinct on (id): two different values in the same kind could in
    -- principle slug to the same id, and a single INSERT … ON CONFLICT
    -- cannot touch one target row twice.
    select distinct on (id) * from (
    select
      kind || ':' || regexp_replace(lower(value), '[^a-z0-9]+', '-', 'g') as id,
      value,
      case kind when 'source' then 'Source' when 'region' then 'Region' else 'Sector' end as segment_group,
      case kind when 'source' then 'source_site' when 'region' then 'region' else 'sector' end as rule_type,
      case kind when 'source' then 300 when 'region' then 400 else 200 end as sort_order
    from present
    where trim(value) <> ''
    ) d
  )
  insert into vd_contact_segments (id, name, description, segment_group, rule, is_generated, sort_order, updated_at)
  select
    d.id, d.value,
    case d.segment_group
      when 'Source' then 'Listed on ' || d.value
      when 'Region' then 'Establishments in ' || d.value
      else d.value || ' establishments'
    end,
    d.segment_group,
    jsonb_build_object('type', d.rule_type, 'value', d.value),
    true, d.sort_order, now()
  from defs d
  on conflict (id) do update set
    name = excluded.name, description = excluded.description,
    segment_group = excluded.segment_group, rule = excluded.rule,
    sort_order = excluded.sort_order, updated_at = now();

  -- A generated segment whose value no longer appears anywhere in the data
  -- is retired. Seeded segments (is_generated = false) always stay, even at
  -- zero members — "nobody is in Converted yet" is itself worth showing.
  delete from vd_contact_segments s
  where s.is_generated
    and not exists (
      select 1 from vd_directory_contacts c
      where (s.rule->>'type' = 'source_site' and (s.rule->>'value') = any(c.source_sites))
         or (s.rule->>'type' = 'region'      and (s.rule->>'value') = any(c.regions))
         or (s.rule->>'type' = 'sector'      and (s.rule->>'value') = any(c.sectors))
    );

  -- (b) Full replace of membership — this function owns every row in
  -- vd_contact_segment_members, so a rebuild is simpler and safer than
  -- reconciling: a contact edited outside it can never leave a stale row.
  delete from vd_contact_segment_members;

  insert into vd_contact_segment_members (segment_id, contact_id, computed_at)
  select s.id, c.id, now()
  from vd_contact_segments s
  join vd_directory_contacts c on
    case s.rule->>'type'
      when 'has_email'       then c.email is not null
      when 'has_phone'       then c.phone is not null
      when 'has_both'        then c.email is not null and c.phone is not null
      when 'unreachable'     then c.email is null and c.phone is null
      when 'contact_status'  then c.contact_status = (s.rule->>'value')
      when 'outreach_status' then c.outreach_status = (s.rule->>'value')
      when 'follow_up_due'   then c.follow_up_date is not null
                                  and c.follow_up_date <= current_date
                                  and c.outreach_status not in ('converted', 'declined')
      when 'source_site'     then (s.rule->>'value') = any(c.source_sites)
      when 'region'          then (s.rule->>'value') = any(c.regions)
      when 'sector'          then (s.rule->>'value') = any(c.sectors)
      when 'category'        then (s.rule->>'value') = any(c.categories)
      else false
    end;
  get diagnostics v_count = row_count;

  return v_count;
end;
$$;
revoke all on function public.vd_apply_contact_segments() from public, anon, authenticated;

create or replace function public.vd_recompute_contact_segments()
returns integer
language plpgsql security definer set search_path = public as $$
begin
  if not (is_admin() or auth.role() = 'service_role') then
    raise exception 'admin only';
  end if;
  return vd_apply_contact_segments();
end;
$$;
grant execute on function public.vd_recompute_contact_segments() to authenticated;
-- Every function here checks is_admin() before it does anything, but leaving
-- them callable by anon still puts an admin-only entry point on the public
-- /rest/v1/rpc surface. The grant to strip is the implicit one to PUBLIC that
-- Postgres puts on every new function — revoking from `anon` alone changes
-- nothing, because anon inherits it through PUBLIC.
revoke execute on function public.vd_recompute_contact_segments() from public;

-- ────────────────────────────────────────────────────────────────────────────
-- 5. Import.
--
-- p_rows is a jsonb array of objects shaped like lib/csv.ts's
-- DirectoryContactRow: establishment (required), contactPerson, emails[],
-- phones[], websites[], socials[], address, bookingUrl, sourceListingUrls[],
-- sourceSites[], categories[], regions[], contactStatus, verifiedOn,
-- priority, outreachStatus, lastContacted, followUpDate, owner,
-- outreachNotes, dataNotes.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.vd_directory_contacts_upsert(p_rows jsonb)
returns integer
language plpgsql set search_path = public as $$
declare
  v_count integer;
begin
  with raw as (
    select
      nullif(trim(r->>'establishment'), '')                       as establishment,
      nullif(trim(r->>'contactPerson'), '')                       as contact_person,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'emails', '[]'::jsonb)) x where trim(x) <> ''), '{}') as emails,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'phones', '[]'::jsonb)) x where trim(x) <> ''), '{}') as phones,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'websites', '[]'::jsonb)) x where trim(x) <> ''), '{}') as websites,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'socials', '[]'::jsonb)) x where trim(x) <> ''), '{}') as socials,
      nullif(trim(r->>'address'), '')                             as address,
      nullif(trim(r->>'bookingUrl'), '')                          as booking_url,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'sourceListingUrls', '[]'::jsonb)) x where trim(x) <> ''), '{}') as source_listing_urls,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'sourceSites', '[]'::jsonb)) x where trim(x) <> ''), '{}') as source_sites,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'categories', '[]'::jsonb)) x where trim(x) <> ''), '{}') as categories,
      coalesce(array(select trim(x) from jsonb_array_elements_text(coalesce(r->'regions', '[]'::jsonb)) x where trim(x) <> ''), '{}') as regions,
      nullif(trim(r->>'contactStatus'), '')                       as contact_status,
      nullif(trim(r->>'verifiedOn'), '')::date                    as verified_on,
      nullif(trim(r->>'priority'), '')                            as priority,
      coalesce(nullif(trim(r->>'outreachStatus'), ''), 'not_contacted') as outreach_status,
      nullif(trim(r->>'lastContacted'), '')::date                 as last_contacted,
      nullif(trim(r->>'followUpDate'), '')::date                  as follow_up_date,
      nullif(trim(r->>'owner'), '')                               as owner,
      coalesce(r->>'outreachNotes', '')                           as outreach_notes,
      coalesce(r->>'dataNotes', '')                               as data_notes,
      ord
    from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb)) with ordinality as t(r, ord)
    where nullif(trim(r->>'establishment'), '') is not null
  ),
  -- A single INSERT … ON CONFLICT DO UPDATE cannot touch the same target row
  -- twice, so a file listing the same establishment more than once would
  -- otherwise abort the whole import. Later rows read as corrections and win.
  deduped as (
    select * from (
      select *, row_number() over (partition by lower(establishment) order by ord desc) as rn from raw
    ) x where rn = 1
  )
  insert into vd_directory_contacts (
    establishment, contact_person, email, emails, phone, phones, websites, socials,
    address, booking_url, source_listing_urls, source_sites, categories, regions, sectors,
    contact_status, verified_on, priority, outreach_status, last_contacted, follow_up_date,
    owner, outreach_notes, data_notes, updated_at
  )
  select
    establishment, contact_person, emails[1], emails, phones[1], phones, websites, socials,
    address, booking_url, source_listing_urls, source_sites, categories, regions,
    vd_directory_sectors(categories),
    contact_status, verified_on, priority, outreach_status, last_contacted, follow_up_date,
    owner, outreach_notes, data_notes, now()
  from deduped
  on conflict (lower(establishment)) do update set
    -- Directory-sourced fields are refreshed from the newer compile…
    establishment       = excluded.establishment,
    contact_person      = coalesce(excluded.contact_person, vd_directory_contacts.contact_person),
    email               = excluded.email,
    emails              = excluded.emails,
    phone               = excluded.phone,
    phones              = excluded.phones,
    websites            = excluded.websites,
    socials             = excluded.socials,
    address             = coalesce(excluded.address, vd_directory_contacts.address),
    booking_url         = coalesce(excluded.booking_url, vd_directory_contacts.booking_url),
    source_listing_urls = excluded.source_listing_urls,
    source_sites        = excluded.source_sites,
    categories          = excluded.categories,
    regions             = excluded.regions,
    sectors             = excluded.sectors,
    contact_status      = excluded.contact_status,
    verified_on         = excluded.verified_on,
    data_notes          = excluded.data_notes,
    -- …while outreach progress is the admin's, not the file's. A re-import
    -- only ever fills a workflow field the file has an opinion about and the
    -- row doesn't; it can never reset a conversation to Not Contacted or
    -- blank someone's notes.
    priority        = coalesce(excluded.priority, vd_directory_contacts.priority),
    outreach_status = case when excluded.outreach_status <> 'not_contacted'
                             and vd_directory_contacts.outreach_status = 'not_contacted'
                           then excluded.outreach_status
                           else vd_directory_contacts.outreach_status end,
    last_contacted  = coalesce(excluded.last_contacted, vd_directory_contacts.last_contacted),
    follow_up_date  = coalesce(excluded.follow_up_date, vd_directory_contacts.follow_up_date),
    owner           = coalesce(excluded.owner, vd_directory_contacts.owner),
    outreach_notes  = case when excluded.outreach_notes <> '' and vd_directory_contacts.outreach_notes = ''
                           then excluded.outreach_notes else vd_directory_contacts.outreach_notes end,
    updated_at      = now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.vd_directory_contacts_upsert(jsonb) from public, anon, authenticated;

create or replace function public.vd_import_directory_contacts(p_rows jsonb)
returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_count integer;
begin
  if not is_admin() then
    raise exception 'admin only';
  end if;
  v_count := vd_directory_contacts_upsert(p_rows);
  perform vd_apply_contact_segments();
  return v_count;
end;
$$;
grant execute on function public.vd_import_directory_contacts(jsonb) to authenticated;
revoke execute on function public.vd_import_directory_contacts(jsonb) from public;

-- ────────────────────────────────────────────────────────────────────────────
-- 6. Outreach edits. Routed through a function rather than a plain UPDATE
--    under the admin policy so segment membership is never left describing
--    the previous status — moving someone to Converted has to move them out
--    of Not Contacted in the same breath.
-- ────────────────────────────────────────────────────────────────────────────
create or replace function public.vd_set_directory_outreach(
  p_id uuid,
  p_outreach_status text default null,
  p_priority text default null,
  p_owner text default null,
  p_last_contacted date default null,
  p_follow_up_date date default null,
  p_outreach_notes text default null
) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then
    raise exception 'admin only';
  end if;

  update vd_directory_contacts set
    -- Every argument is "leave it alone when null", except the two dates and
    -- the owner, which need a way to be cleared: passing the empty string
    -- for p_owner / p_outreach_notes, or 'clear' via p_outreach_status, is
    -- not overloaded here — a caller clearing a date sends the sentinel
    -- '1900-01-01', which no real outreach date can be.
    outreach_status = coalesce(nullif(trim(p_outreach_status), ''), outreach_status),
    priority        = case when p_priority is null then priority
                           when trim(p_priority) = '' then null
                           else trim(p_priority) end,
    owner           = case when p_owner is null then owner
                           when trim(p_owner) = '' then null
                           else trim(p_owner) end,
    last_contacted  = case when p_last_contacted is null then last_contacted
                           when p_last_contacted = date '1900-01-01' then null
                           else p_last_contacted end,
    follow_up_date  = case when p_follow_up_date is null then follow_up_date
                           when p_follow_up_date = date '1900-01-01' then null
                           else p_follow_up_date end,
    outreach_notes  = coalesce(p_outreach_notes, outreach_notes),
    updated_at      = now()
  where id = p_id;

  if not found then
    raise exception 'contact not found';
  end if;

  perform vd_apply_contact_segments();
end;
$$;
grant execute on function public.vd_set_directory_outreach(uuid, text, text, text, date, date, text) to authenticated;
revoke execute on function public.vd_set_directory_outreach(uuid, text, text, text, date, date, text) from public;
