export type TrailGrade = 'Easy' | 'Moderate' | 'Challenging' | 'Difficult' | 'Extreme'
export type DifficultyBand = 'easy' | 'moderate' | 'difficult' | 'extreme'

export type GpxPoint = { lat: number; lon: number; ele: number; name?: string; type?: string; time?: string; distanceKm: number }
export type TrailSection = { startIndex: number; endIndex: number; distanceKm: number; elevationChangeM: number; slopePct: number; gradientPct: number; directionDeg: number; effort: number; difficultyScore: number; terrain: string; band: DifficultyBand }
export type TrailCrux = { id: string; pointIndex: number; lat: number; lon: number; distanceKm: number; elevationM: number; severity: TrailGrade; description: string; adminNotes?: string }
export type TrailWaypoint = { id: string; lat: number; lon: number; elevationM?: number; distanceKm?: number; name: string; category: 'Camp' | 'Water' | 'Viewpoint' | 'Pass' | 'Peak' | 'Parking' | 'Emergency Exit' | 'Scramble' | 'Bridge' | 'River Crossing' | 'Shelter' | 'Summit' | 'Start' | 'Finish' }
export type SlopeDistribution = { label: string; min: number; max: number | null; percent: number; distanceKm: number; band: DifficultyBand }[]
export type GpxStatistics = {
  totalDistanceKm: number; movingDistanceKm: number; maximumElevationM: number; minimumElevationM: number; totalAscentM: number; totalDescentM: number; averageElevationM: number; averageGradientPct: number; maximumGradientPct: number; averageSlopePct: number; maximumSlopePct: number; elevationGainPerKm: number; estimatedHikingTimeHours: number; estimatedTrailRunningTimeHours: number; estimatedNavigationTimeHours: number; trackPointCount: number; waypointCount: number; trailLengthKm: number; elevationRangeM: number; longestClimbKm: number; longestDescentKm: number; steepestClimbPct: number; steepestDescentPct: number; movingPaceMinPerKm: number; hikingPaceMinPerKm: number; runningPaceMinPerKm: number; averageClimbAngleDeg: number; maximumClimbAngleDeg: number; totalClimbingTimeHours: number; totalDescendingTimeHours: number
}
export type GpxAnalysis = { metadata: { processedAt: string; source: 'gpx' | 'synthetic'; supported: string[] }; points: GpxPoint[]; waypoints: TrailWaypoint[]; sections: TrailSection[]; cruxes: TrailCrux[]; slopeDistribution: SlopeDistribution; statistics: GpxStatistics; automaticGrade: TrailGrade; automaticScore: number; automaticExplanation: string; routeArtworkSvg: string }

const R = 6371000
const rad = (v: number) => v * Math.PI / 180
const clamp = (v:number,min:number,max:number)=>Math.max(min,Math.min(max,v))
const distM = (a:GpxPoint,b:GpxPoint)=>{const dLat=rad(b.lat-a.lat),dLon=rad(b.lon-a.lon);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
const bearing = (a:GpxPoint,b:GpxPoint)=>{const y=Math.sin(rad(b.lon-a.lon))*Math.cos(rad(b.lat));const x=Math.cos(rad(a.lat))*Math.sin(rad(b.lat))-Math.sin(rad(a.lat))*Math.cos(rad(b.lat))*Math.cos(rad(b.lon-a.lon));return (Math.atan2(y,x)*180/Math.PI+360)%360}
const bandFor = (score:number):DifficultyBand => score >= 82 ? 'extreme' : score >= 58 ? 'difficult' : score >= 34 ? 'moderate' : 'easy'
const gradeFor = (score:number):TrailGrade => score >= 85 ? 'Extreme' : score >= 68 ? 'Difficult' : score >= 48 ? 'Challenging' : score >= 26 ? 'Moderate' : 'Easy'

export function analyseGpx(gpxText: string): GpxAnalysis {
  const xml = new DOMParser().parseFromString(gpxText, 'application/xml')
  if (xml.querySelector('parsererror')) throw new Error('Invalid GPX XML')
  const readPoint = (el: Element, fallbackType?: string): GpxPoint => ({ lat: Number(el.getAttribute('lat')), lon: Number(el.getAttribute('lon')), ele: Number(el.querySelector('ele')?.textContent || 0), name: el.querySelector('name')?.textContent || undefined, type: el.querySelector('type')?.textContent || fallbackType, time: el.querySelector('time')?.textContent || undefined, distanceKm: 0 })
  let points = [...xml.querySelectorAll('trkseg trkpt')].map(e => readPoint(e, 'track'))
  if (!points.length) points = [...xml.querySelectorAll('rte rtept')].map(e => readPoint(e, 'route'))
  const waypoints: TrailWaypoint[] = [...xml.querySelectorAll('wpt')].map((e, i) => { const p = readPoint(e, 'waypoint'); return { id: `wpt-${i}`, lat: p.lat, lon: p.lon, elevationM: p.ele, name: p.name || `Waypoint ${i+1}`, category: categoriseWaypoint(p.name || p.type || '') } })
  if (points.length < 2) throw new Error('GPX needs at least two track or route points')
  points = points.filter(p => Number.isFinite(p.lat) && Number.isFinite(p.lon))
  let totalM = 0; const sections: TrailSection[] = []
  for (let i=1;i<points.length;i++) { const d=distM(points[i-1],points[i]); totalM += d; points[i].distanceKm = totalM/1000; const elev=points[i].ele-points[i-1].ele; const slope=d>0 ? elev/d*100 : 0; const score=clamp(Math.abs(slope)*2.1 + (elev>0?8:3) + (d<35&&Math.abs(slope)>18?18:0), 5, 100); const terrain = Math.abs(slope)>30?'technical terrain':slope>18?'steep climb':slope<-18?'steep descent':Math.abs(slope)<5?'recovery section':'rolling section'; sections.push({startIndex:i-1,endIndex:i,distanceKm:d/1000,elevationChangeM:elev,slopePct:slope,gradientPct:slope,directionDeg:bearing(points[i-1],points[i]),effort:score/10,difficultyScore:score,terrain,band:bandFor(score)}) }
  const elevs = points.map(p=>p.ele); const ascent=sections.filter(s=>s.elevationChangeM>0).reduce((a,s)=>a+s.elevationChangeM,0); const descent=Math.abs(sections.filter(s=>s.elevationChangeM<0).reduce((a,s)=>a+s.elevationChangeM,0));
  const cruxes = detectCruxes(points, sections)
  const avgSlope = sections.reduce((a,s)=>a+Math.abs(s.slopePct)*s.distanceKm,0)/(totalM/1000 || 1)
  const score = clamp((totalM/1000)*1.5 + ascent/45 + Math.max(...sections.map(s=>Math.abs(s.slopePct)))*1.4 + avgSlope*1.8 + cruxes.length*5 + Math.max(...elevs)/250, 1, 100)
  const grade = gradeFor(score); const hikeH = (totalM/1000)/4 + ascent/600 + cruxes.length*0.12
  const stats: GpxStatistics = { totalDistanceKm: totalM/1000, movingDistanceKm: totalM/1000, maximumElevationM: Math.max(...elevs), minimumElevationM: Math.min(...elevs), totalAscentM: ascent, totalDescentM: descent, averageElevationM: elevs.reduce((a,b)=>a+b,0)/elevs.length, averageGradientPct: sections.reduce((a,s)=>a+s.gradientPct*s.distanceKm,0)/(totalM/1000 || 1), maximumGradientPct: Math.max(...sections.map(s=>Math.abs(s.gradientPct))), averageSlopePct: avgSlope, maximumSlopePct: Math.max(...sections.map(s=>Math.abs(s.slopePct))), elevationGainPerKm: ascent/(totalM/1000 || 1), estimatedHikingTimeHours: hikeH, estimatedTrailRunningTimeHours: hikeH*0.42, estimatedNavigationTimeHours: hikeH*(1+cruxes.length*0.04), trackPointCount: points.length, waypointCount: waypoints.length, trailLengthKm: totalM/1000, elevationRangeM: Math.max(...elevs)-Math.min(...elevs), longestClimbKm: longestRun(sections, true), longestDescentKm: longestRun(sections, false), steepestClimbPct: Math.max(...sections.map(s=>s.slopePct)), steepestDescentPct: Math.min(...sections.map(s=>s.slopePct)), movingPaceMinPerKm: hikeH*60/(totalM/1000 || 1), hikingPaceMinPerKm: hikeH*60/(totalM/1000 || 1), runningPaceMinPerKm: hikeH*0.42*60/(totalM/1000 || 1), averageClimbAngleDeg: Math.atan(avgSlope/100)*180/Math.PI, maximumClimbAngleDeg: Math.atan(Math.max(...sections.map(s=>Math.abs(s.slopePct)))/100)*180/Math.PI, totalClimbingTimeHours: ascent/600, totalDescendingTimeHours: descent/900 }
  return { metadata:{processedAt:new Date().toISOString(), source:'gpx', supported:['tracks','segments','routes','waypoints']}, points, waypoints, sections, cruxes, slopeDistribution: slopeDistribution(sections), statistics: stats, automaticGrade: grade, automaticScore: Math.round(score), automaticExplanation: `${grade} from ${stats.totalDistanceKm.toFixed(1)} km, ${Math.round(ascent)} m ascent, ${stats.maximumSlopePct.toFixed(0)}% max slope and ${cruxes.length} detected cruxes.`, routeArtworkSvg: generateRouteArtwork(points) }
}
export const analyseGpxAsync = (gpxText:string) => new Promise<GpxAnalysis>((resolve,reject)=>setTimeout(()=>{try{resolve(analyseGpx(gpxText))}catch(e){reject(e)}},0))
function categoriseWaypoint(v:string):TrailWaypoint['category'] { const s=v.toLowerCase(); if(s.includes('water'))return'Water'; if(s.includes('camp'))return'Camp'; if(s.includes('pass'))return'Pass'; if(s.includes('peak')||s.includes('summit'))return'Peak'; if(s.includes('river'))return'River Crossing'; if(s.includes('view'))return'Viewpoint'; if(s.includes('parking'))return'Parking'; return 'Viewpoint' }
function detectCruxes(points:GpxPoint[], sections:TrailSection[]):TrailCrux[]{return sections.filter(s=>Math.abs(s.slopePct)>24||s.difficultyScore>70).filter((_,i)=>i%3===0).slice(0,12).map((s,i)=>{const p=points[s.endIndex];return{id:`crux-${i}`,pointIndex:s.endIndex,lat:p.lat,lon:p.lon,distanceKm:p.distanceKm,elevationM:p.ele,severity:gradeFor(s.difficultyScore),description:s.slopePct>0?`Very steep climb averaging ${s.slopePct.toFixed(0)}%.`:`Steep/technical descent averaging ${Math.abs(s.slopePct).toFixed(0)}%.`}})}
function slopeDistribution(sections:TrailSection[]):SlopeDistribution{const bins=[['0–5%',0,5,'easy'],['5–10%',5,10,'moderate'],['10–15%',10,15,'moderate'],['15–20%',15,20,'difficult'],['20–30%',20,30,'difficult'],['30%+',30,null,'extreme']] as const; const total=sections.reduce((a,s)=>a+s.distanceKm,0)||1; return bins.map(([label,min,max,band])=>{const d=sections.filter(s=>Math.abs(s.slopePct)>=min&&(max===null||Math.abs(s.slopePct)<max)).reduce((a,s)=>a+s.distanceKm,0); return {label,min,max,percent:d/total*100,distanceKm:d,band}})}
function longestRun(sections:TrailSection[], climb:boolean){let best=0,cur=0; sections.forEach(s=>{if((climb&&s.elevationChangeM>0)||(!climb&&s.elevationChangeM<0)){cur+=s.distanceKm; best=Math.max(best,cur)}else cur=0}); return best}
export function generateRouteArtwork(points:GpxPoint[]):string{const w=300,h=160,pad=14; const lats=points.map(p=>p.lat),lons=points.map(p=>p.lon); const minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons); const path=points.map((p,i)=>`${i?'L':'M'} ${pad+((p.lon-minLon)/(maxLon-minLon||1))*(w-pad*2)} ${h-pad-((p.lat-minLat)/(maxLat-minLat||1))*(h-pad*2)}`).join(' '); return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" fill="none"><path d="${path}" stroke="#2d6a4f" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
