import type { TourDate } from '@/components/tours/UpcomingDepartures'

// Upcoming departures keyed by trail or activity id.
// Dates are from July 2026 onwards (today = June 23 2026).
export const TOUR_DATES: Record<string, TourDate[]> = {

  /* ── TRAIL: Tugela Falls Circuit ─────────────────────────── */
  'tugela-falls': [
    {
      id: 'tf-g-1',
      date: '2026-07-05',
      type: 'guide',
      operator: 'Sipho Dlamini — Certified Berg Guide',
      guide: 'Sipho Dlamini',
      spots_total: 8,
      spots_remaining: 3,
      price_per_person: 890,
      duration: '7–9 hrs',
      notes: 'Includes park permit & breakfast pack',
    },
    {
      id: 'tf-g-2',
      date: '2026-07-19',
      type: 'guide',
      operator: 'Thabo Ndlovu — Wilderness Guides',
      guide: 'Thabo Ndlovu',
      spots_total: 6,
      spots_remaining: 6,
      price_per_person: 950,
      duration: '7–9 hrs',
      notes: 'Small group — max 6',
    },
    {
      id: 'tf-pkg-1',
      date: '2026-08-02',
      type: 'package',
      operator: 'Royal Natal 3-Night Package',
      spots_total: 12,
      spots_remaining: 0,
      price_per_person: 4200,
      duration: '3 days / 2 nights',
      notes: 'Accommodation at Tendele + 2 guided hikes',
    },
    {
      id: 'tf-g-3',
      date: '2026-08-09',
      type: 'guide',
      operator: 'Sipho Dlamini — Certified Berg Guide',
      guide: 'Sipho Dlamini',
      spots_total: 8,
      spots_remaining: 8,
      price_per_person: 890,
      duration: '7–9 hrs',
    },
    {
      id: 'tf-pkg-2',
      date: '2026-09-06',
      type: 'package',
      operator: 'Berg Highlights Weekend',
      spots_total: 16,
      spots_remaining: 9,
      price_per_person: 3800,
      duration: '2 days / 1 night',
      notes: 'Tugela Falls + Amphitheatre on day 2',
    },
  ],

  /* ── TRAIL: Amphitheatre via Chain Ladder ────────────────── */
  'amphitheatre': [
    {
      id: 'am-g-1',
      date: '2026-07-11',
      type: 'guide',
      operator: 'Anele Mokoena — Day Hike Specialist',
      guide: 'Anele Mokoena',
      spots_total: 10,
      spots_remaining: 4,
      price_per_person: 780,
      duration: '4–5 hrs',
      notes: 'Kid-friendly departure (12+)',
    },
    {
      id: 'am-g-2',
      date: '2026-07-25',
      type: 'guide',
      operator: 'Thabo Ndlovu — Wilderness Guides',
      guide: 'Thabo Ndlovu',
      spots_total: 8,
      spots_remaining: 2,
      price_per_person: 820,
      duration: '4–5 hrs',
    },
    {
      id: 'am-exp-1',
      date: '2026-08-16',
      type: 'experience',
      operator: 'Sunrise Chain Ladder Climb',
      guide: 'Sipho Dlamini',
      spots_total: 6,
      spots_remaining: 6,
      price_per_person: 1100,
      duration: '5 hrs (4am start)',
      notes: 'Summit at sunrise — limited spots',
    },
  ],

  /* ── TRAIL: Cathedral Peak Summit ────────────────────────── */
  'cathedral-peak': [
    {
      id: 'cp-g-1',
      date: '2026-07-18',
      type: 'guide',
      operator: 'Thabo Ndlovu — Wilderness Guides',
      guide: 'Thabo Ndlovu',
      spots_total: 6,
      spots_remaining: 1,
      price_per_person: 1050,
      duration: '8–10 hrs',
      notes: 'Technical summit — fitness assessment required',
    },
    {
      id: 'cp-pkg-1',
      date: '2026-08-22',
      type: 'package',
      operator: 'Cathedral Peak Hotel Summit Package',
      spots_total: 8,
      spots_remaining: 5,
      price_per_person: 5600,
      duration: '2 days / 1 night',
      notes: '1-night stay at Cathedral Peak Hotel + guided summit',
    },
  ],

  /* ── TRAIL: Grand Traverse (multi-day) ───────────────────── */
  'grand-traverse': [
    {
      id: 'gt-g-1',
      date: '2026-07-26',
      type: 'guide',
      operator: 'Berg Traverse Expeditions',
      guide: 'Sipho Dlamini + Thabo Ndlovu',
      spots_total: 8,
      spots_remaining: 3,
      price_per_person: 18500,
      duration: '14–18 days',
      notes: 'Full gear and food provided',
    },
    {
      id: 'gt-g-2',
      date: '2026-09-13',
      type: 'guide',
      operator: 'Berg Traverse Expeditions',
      guide: 'Sipho Dlamini + Thabo Ndlovu',
      spots_total: 8,
      spots_remaining: 8,
      price_per_person: 18500,
      duration: '14–18 days',
    },
  ],

  /* ── TRAIL: Giant's Castle via Meander ───────────────────── */
  'giants-castle': [
    {
      id: 'gc-g-1',
      date: '2026-07-12',
      type: 'guide',
      operator: 'Anele Mokoena — Day Hike Specialist',
      guide: 'Anele Mokoena',
      spots_total: 10,
      spots_remaining: 7,
      price_per_person: 860,
      duration: '7–9 hrs',
      notes: 'Lammergeier hide visit included',
    },
    {
      id: 'gc-exp-1',
      date: '2026-08-01',
      type: 'experience',
      operator: 'Rock Art & Hike Combo',
      guide: 'Lerato Sithole + Anele Mokoena',
      spots_total: 8,
      spots_remaining: 4,
      price_per_person: 1350,
      duration: 'Full day',
      notes: 'Heritage guide joins for San rock art interpretation',
    },
  ],

  /* ── ACTIVITY: Guided Rock Climbing ─────────────────────── */
  'a1': [
    {
      id: 'rc-1',
      date: '2026-07-05',
      type: 'experience',
      operator: 'Drakensberg Adventures',
      guide: 'Sipho Dlamini',
      spots_total: 8,
      spots_remaining: 5,
      price_per_person: 750,
      duration: 'Full day (6–8 hrs)',
      notes: 'Beginner-friendly routes',
    },
    {
      id: 'rc-2',
      date: '2026-07-12',
      type: 'experience',
      operator: 'Drakensberg Adventures',
      guide: 'Bongani Khumalo',
      spots_total: 8,
      spots_remaining: 8,
      price_per_person: 750,
      duration: 'Full day (6–8 hrs)',
    },
    {
      id: 'rc-3',
      date: '2026-07-19',
      type: 'experience',
      operator: 'Drakensberg Adventures',
      guide: 'Sipho Dlamini',
      spots_total: 6,
      spots_remaining: 2,
      price_per_person: 950,
      duration: 'Full day',
      notes: 'Advanced multi-pitch routes — prior experience required',
    },
    {
      id: 'rc-pkg-1',
      date: '2026-08-09',
      type: 'package',
      operator: 'Climb & Stay Weekend',
      spots_total: 10,
      spots_remaining: 6,
      price_per_person: 2800,
      duration: '2 days / 1 night',
      notes: 'Accommodation + 2 climbing sessions + meals',
    },
    {
      id: 'rc-4',
      date: '2026-08-23',
      type: 'experience',
      operator: 'Drakensberg Adventures',
      guide: 'Bongani Khumalo',
      spots_total: 8,
      spots_remaining: 8,
      price_per_person: 750,
      duration: 'Full day (6–8 hrs)',
    },
  ],

  /* ── ACTIVITY: San Rock Art Tour ─────────────────────────── */
  'a2': [
    {
      id: 'ra-1',
      date: '2026-07-08',
      type: 'guide',
      operator: 'Berg Cultural Tours',
      guide: 'Lerato Sithole',
      spots_total: 15,
      spots_remaining: 9,
      price_per_person: 620,
      duration: 'Full day',
      notes: "Giant's Castle Main Caves",
    },
    {
      id: 'ra-2',
      date: '2026-07-22',
      type: 'guide',
      operator: 'Berg Cultural Tours',
      guide: 'Lerato Sithole',
      spots_total: 15,
      spots_remaining: 0,
      price_per_person: 620,
      duration: 'Full day',
    },
    {
      id: 'ra-exp-1',
      date: '2026-08-05',
      type: 'experience',
      operator: 'Rock Art Photography Day',
      guide: 'Lerato Sithole',
      spots_total: 8,
      spots_remaining: 3,
      price_per_person: 950,
      duration: 'Full day',
      notes: 'Specialist photography guide included',
    },
    {
      id: 'ra-pkg-1',
      date: '2026-08-19',
      type: 'package',
      operator: 'San Heritage 2-Day Experience',
      spots_total: 10,
      spots_remaining: 7,
      price_per_person: 3200,
      duration: '2 days / 1 night',
      notes: 'Accommodation at Berg Guesthouse + 2 rock art tours',
    },
    {
      id: 'ra-3',
      date: '2026-09-02',
      type: 'guide',
      operator: 'Berg Cultural Tours',
      guide: 'Lerato Sithole',
      spots_total: 15,
      spots_remaining: 15,
      price_per_person: 620,
      duration: 'Full day',
    },
  ],
}

export function getTourDates(id: string): TourDate[] {
  return TOUR_DATES[id] ?? []
}
