'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { Users, Plus, Car } from 'lucide-react'
import { supabase } from '@/lib/auth'
import { getSupplierEntities, type SupplierEntity } from '@/lib/supplier-entities'

type Driver = SupplierEntity & { name?: string; fullName?: string; license?: string; licenseType?: string; languages: string; trips?: number; status: string }
export default function DriversPage() { const [drivers, setDrivers] = useState<Driver[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { async function load() { const { data } = await supabase.auth.getUser(); if (data.user) setDrivers(await getSupplierEntities<Driver>('drivers', data.user.id)); setLoading(false) } load() }, []); return <div className="p-8 space-y-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Users size={20} className="text-[#C9A96E]" /><h1 className="font-display italic text-2xl text-black/90">Drivers</h1></div><Link href="/supplier/drivers/new" className="flex items-center gap-2 bg-[#C9A96E] text-white font-sans text-sm px-4 py-2 rounded-lg hover:bg-[#b8965d] transition-colors"><Plus size={15} /> Add Driver</Link></div>{loading ? <p className="font-sans text-sm text-black/40">Loading drivers…</p> : drivers.length === 0 ? <p className="font-sans text-sm text-black/40">No drivers yet.</p> : <div className="grid gap-3">{drivers.map(d => { const name = d.fullName ?? d.name ?? 'Driver'; return <div key={d.id} className="bg-white rounded-xl border border-black/8 p-5 flex items-center gap-4"><div className="w-10 h-10 rounded-full bg-[#C9A96E]/10 flex items-center justify-center shrink-0"><span className="font-sans text-sm font-semibold text-[#C9A96E]">{name.split(' ').map(n => n[0]).join('')}</span></div><div className="flex-1 min-w-0"><p className="font-sans font-semibold text-black/90">{name}</p><div className="flex items-center gap-4 mt-1"><span className="font-sans text-xs text-black/40">License: {d.licenseType ?? d.license}</span><span className="font-sans text-xs text-black/40">{d.languages}</span><span className="font-sans text-xs text-black/40 flex items-center gap-1"><Car size={11} /> {d.trips ?? 0} trips</span></div></div><div className="flex items-center gap-3 shrink-0"><span className="font-sans text-xs px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700">{d.status}</span><Link href={`/supplier/drivers/${d.id}/edit`} className="font-sans text-xs text-[#C9A96E] hover:underline">Edit</Link></div></div>})}</div>}</div> }
